services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=tpSpring
      - MYSQL_ROOT_PASSWORD=P4ssword!
    ports:
      - 3307:3306
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge