services:
  mysql:
    image: mysql:9.1
    environment:
      - MYSQL_DATABASE=tpE8Impl
      - MYSQL_ROOT_PASSWORD=tpE8Impl
    ports:
      - 3307:3306
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge